-- SQLite
$sqlite3 my.db

CREATE TABLE TODOTABLE(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   TODO TEXT
);

SELECT * FROM TODOTABLE

DROP TABLE TODOTABLE

INSERT INTO TODOTABLE (TODO) VALUES ('SAYA')

DELETE FROM TODOTABLE