-- SQLite
$sqlite3 my.db

CREATE TABLE TODOTABLE(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   TODO TEXT
);

CREATE TABLE USER(
   ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   USERNAME TEXT,
   PASSWORD TEXT
);

SELECT * FROM TODOTABLE

SELECT * FROM USER

DROP TABLE TODOTABLE

INSERT INTO TODOTABLE (TODO) VALUES ('SAYA')

INSERT INTO USER (USERNAME, PASSWORD) VALUES ('Budi', '1234')

DELETE FROM USER